### ISSUE TITLE
error in ubuntu/WSL2

### ISSUE THREAD

**Issue by cswaroop** [borkdude/nbb#27]
$ nbb -e '(+ 1 2 3)'
/usr/local/lib/node_modules/nbb/out/nbb_main.js:3
import * as import$fs from "fs";
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by borkdude** [comment]
@cswaroop It seems you're using an old version of Node which doesn't understand `import`.

**Comment by borkdude** [comment]
I tested with version 12 and that seems to work:
```
borkdude@MBP2019 /tmp $ docker run --rm -it node:12 /bin/bash
root@ab31f2850c46:/# npm install -g nbb
/usr/local/bin/nbb -> /usr/local/lib/node_modules/nbb/out/nbb_main.js
+ nbb@0.0.20
added 12 packages from 6 contributors in 2.776s
root@ab31f2850c46:/# nbb -e '(+ 1 2 3)'
6
```

**Comment by borkdude** [comment]
But with v11 I can reproduce your issue above.

**Comment by borkdude** [comment]
Updated the README with this information. Please confirm and close the issue if that solves it for you.

**Comment by cswaroop** [comment]
Yes. I have older version of node.  Thanks it works after updating node and npm
